INSERT INTO Practices (
		ISNGONDRO,
		SORT_ORDER,
		RESOURCEIDICON,
		RESOURCEIDTITLE,
		TOTALCOUNT,
		SCHEDULEDCOMPLETION) values (
		1, 0, 100, 500, 111111, 0
		);
		
		
INSERT INTO Practices (
		ISNGONDRO,
		SORT_ORDER,
		ICONURL,
		TITLE,
		TOTALCOUNT,
		SCHEDULEDCOMPLETION) values (
		1, 1, 'file://icon.png', 'Dorje sempa', 111111, 0
		);
		
INSERT INTO PracticeHistory (PRACTICE_ID, DONE_COUNT) values (1, 108);
INSERT INTO PracticeHistory (PRACTICE_ID, DONE_COUNT) values (1, 114);
INSERT INTO PracticeHistory (PRACTICE_ID, DONE_COUNT) values (2, 124);
INSERT INTO PracticeHistory (PRACTICE_ID, DONE_COUNT) values (1, 120);

