select ICONURL, THUMBURL, TITLE, TOTALCOUNT, SCHEDULEDCOMPLETION,  
SUM(DONE_COUNT) as DONE, 100.0*SUM(DONE_COUNT)/TOTALCOUNT as DONE_PERC ,
MAX(PRACTICE_DATE) AS LAST_PRACTICE

from practices p join practiceHistory ph on p._ID = ph.PRACTICE_ID
WHERE ISNGONDRO = 1 
GROUP BY p._ID
ORDER BY SORT_ORDER;